---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfcontainerization/base-ci
    tag: latest
inputs:
- name: ci
- name: docker-image-resource
- name: buildpack
- name: s3.stemcell-version
- name: s3.fissile-linux
params:
  STEMCELL_OS:
  STEMCELL_REPOSITORY:
  BUILDPACK_NAME:
  DOCKER_ORGANIZATION:
  DOCKER_TEAM_USERNAME:
  DOCKER_TEAM_PASSWORD_RW:
run:
  path: ci/pipelines/release-images/tasks/build.sh
