---
platform: linux
image_resource:
 type: docker-image
 source:
   repository: cfcontainerization/go-tools
   tag: latest
inputs:
- name: ci
- name: src
run:
  path: ci/pipelines/rohit-test/tasks/push.sh
