<%
buildpacks_releases = %w(binary-buildpack dotnet-core-buildpack go-buildpack java-buildpack nodejs-buildpack php-buildpack python-buildpack ruby-buildpack staticfile-buildpack)

releases = buildpacks_releases.map { |r| { organization: "cloudfoundry", name: r } }
%>

resources:
- name: ci
  type: git
  source:
    uri: ((ci-repo))
    branch: ((ci-branch))
<% releases.each do |release| %>
- name: <%= release[:name] %>-release
  type: bosh-io-release
  source:
    repository: <%= release[:organization] %>/<%= release[:name] %>-release
<% end %>
- name: s3.fissile-linux
  type: s3
  source:
    bucket: ((fissile-linux-s3-bucket))
    private: true
    regexp: fissile/develop/fissile-(.*)\.tgz

- name: s3.fissile-stemcell-version
  type: s3
  source:
    bucket: ((stemcell-versions-s3-bucket))
    region_name: ((stemcell-s3-bucket-region))
    access_key_id: ((s3.accessKey))
    secret_access_key: ((s3.secretKey))
    versioned_file: ((stemcell-version-file))

jobs:
<% (releases + s3_releases).each do |release| %>
- name: build-<%= release[:name] %>
  plan:
  - in_parallel:
    - get: ci
  - in_parallel:
    - get: s3.fissile-stemcell-version
      trigger: true
    - get: <%= release[:name] %>-release
      trigger: true
      params:
        tarball: false
    - get: s3.fissile-linux
      trigger: true
  - do:
    - task: build
      privileged: true
      input_mapping:
        release: <%= release[:name] %>-release
        s3.stemcell-version: s3.fissile-stemcell-version
      params:
        STEMCELL_OS: ((stemcell-os))
        STEMCELL_REPOSITORY: ((stemcell-repository))
        STEMCELL_VERSIONED_FILE: ((stemcell-version-file))
        RELEASE_NAME: <%= release[:name] %>
        DOCKER_REGISTRY: ((docker-registry))
        DOCKER_ORGANIZATION: ((docker-organization))
        DOCKER_TEAM_USERNAME: ((dockerhub.username))
        DOCKER_TEAM_PASSWORD_RW: ((dockerhub.password))
      file: ci/pipelines/release-images/tasks/build.yml
<% end %>
