---
resources:
- name: sample-resource
  type: s3
  tags: [containerization]
  source:
    access_key_id: ((cos-access-key-id))
    secret_access_key: ((cos-secret-access-key))
    bucket: unique-bbuccket
    endpoint: ((cos-endpoint))
    disable_ssl: true
    regexp: hello-(.*).tar.gz


jobs:
- name: hello-world
  plan:
  - get: sample-resource
    tags: [containerization]
  - task: hello-inline
    tags: [containerization]
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: bionic
      params:
        GREETING: ((secret-greeting))
      run:
        path: /bin/bash
        args:
        - -c
        - |
          #!/bin/sh

          echo "Hello, ${GREETING}!"
  - task: hello-inline-with-resource
    tags: [containerization]
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: bionic
      inputs:
      - name: sample-resource
      params:
        GREETING: ((secret-greeting))
      run:
        path: /bin/bash
        args:
        - -c
        - |
          #!/bin/sh
          tar -xzf sample-resource/hello-world.tar.gz
          cat hello-world.yml
  - task: hello-script
    tags: [containerization]
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: bionic
      params:
        GREETING: ((greeting))
      run:
        path: /bin/bash
        args:
        - -c
        - (( file "scripts/hello-greeting.sh" ))
