---
platform: linux
image_resource:
 type: docker-image
 source:
   repository: cfcontainerization/go-tools
   tag: latest
inputs:
- name: src
  path: src/code.cloudfoundry.org/cf-operator
- name: ci
outputs:
- name: binaries
- name: docker
caches:
- path: pkg/mod # Persist go modules cache
run:
  path: /bin/bash
  args:
  - -c
  - |
    #!/usr/bin/env sh
    set -ex

    export PATH=$PATH:$PWD/bin
    export GOPATH=$PWD
    export GO111MODULE=on

    pushd src/code.cloudfoundry.org/cf-operator
    git describe --tags --long || git tag v0.0.0 # Make sure there's always a tag that can be used for building the version
    . bin/include/versioning
    popd

    set -ex
    make -C src/code.cloudfoundry.org/cf-operator build
    cp src/code.cloudfoundry.org/cf-operator/binaries/cf-operator binaries/cf-operator-$VERSION_TAG
    echo $VERSION_TAG > docker/tag
