---
platform: linux
image_resource:
 type: docker-image
 source:
   repository: cfcontainerization/go-tools
   tag: latest
inputs:
- name: src
  path: src/code.cloudfoundry.org/cf-operator
- name: ci
caches:
- path: pkg/mod # Persist go modules cache
run:
  path: /bin/bash
  args:
  - -c
  - |
    #!/usr/bin/env sh
    set -eu

    export PATH=$PATH:$PWD/bin
    export GOPATH=$PWD
    export GO111MODULE=on

    ibmcloud login -a "$ibmcloud_server" --apikey "$ibmcloud_apikey"
    ibmcloud cs  region-set "$ibmcloud_region"
    eval $(ibmcloud cs cluster-config "$ibmcloud_cluster" --export)

    make -C src/code.cloudfoundry.org/cf-operator test-integration

