---
platform: linux
image_resource:
 type: docker-image
 source:
   repository: cfcontainerization/go-tools
   tag: latest
inputs:
- name: src
  path: src/code.cloudfoundry.org/cf-operator
- name: ci
caches:
- path: pkg/mod # Persist go modules cache
run:
  path: /bin/bash
  args:
  - -c
  - |
    #!/usr/bin/env sh
    set -ex

    export PATH=$PATH:$PWD/bin
    export GOPATH=$PWD
    export GO111MODULE=on

    make -C src/code.cloudfoundry.org/cf-operator vet