---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfcontainerization/go-tools
    tag: latest
inputs:
- name: ci
- name: kubecf-src
- name: s3.shas
- name: s3.release.helm-charts
run:
  path: ci/pipelines/cf-operator-release/tasks/create-pr.sh
