---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfcontainerization/go-tools
    tag: latest
inputs:
- name: ci
- name: s3.release.helm-charts
- name: helm-repo
outputs:
- name: updated
run:
  path: ci/pipelines/cf-operator-release/tasks/helm-repo.sh
