resources:
- name: src
  type: git
  tags: [containerization]
  source:
    uri: ((src-repo))
    branch: master
- name: ci
  type: git
  tags: [containerization]
  source:
    uri: ((ci-repo))
    branch: ((ci-branch))
- name: docker.cf-operator-rc
  type: docker-image
  tags: [containerization]
  source:
    repository: ((docker-organization))/((docker-candidate-repo))
    username: ((dockerhub.username))
    password: ((dockerhub.password))
- name: 12h
  type: time
  source:
    interval: 12h

jobs:
- name: test
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: src
      passed: [build]
      trigger: true
    - get: 12h
      trigger: true
  - task: vet
    tags: [containerization]
    file: ci/pipelines/cf-operator/tasks/vet.yml
  - task: lint
    tags: [containerization]
    file: ci/pipelines/cf-operator/tasks/lint.yml
  - task: test-unit
    tags: [containerization]
    file: ci/pipelines/cf-operator/tasks/test.yml
  - task: test-integration
    tags: [containerization]
    params:
      ibmcloud_apikey: ((ibmcloud.key-value))
      ibmcloud_server: ((ibmcloud.server))
      ibmcloud_region: ((ibmcloud.region))
      ibmcloud_cluster: ((ibmcloud.cluster))
      ssh_server_ip: ((ssh-server.ip))
      ssh_server_user: ((ssh-server.user))
      ssh_server_key: ((ssh-server.key))
      COVERALLS_TOKEN: ((coveralls-token))
      OPERATOR_TEST_STORAGE_CLASS: ((storageclass))
      DOCKER_IMAGE_REPOSITORY: ((docker-candidate-repo))
    file: ci/pipelines/cf-operator/tasks/test-integration.yml
  - task: coverage
    tags: [containerization]
    params:
      COVERALLS_TOKEN: ((coveralls-token))
    file: ci/pipelines/cf-operator/tasks/coverage.yml

- name: build
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: src
    - get: 12h
      trigger: true
  - task: build
    tags: [containerization]
    file: ci/pipelines/cf-operator/tasks/build.yml
  - put: docker.cf-operator-rc
    params:
      build: src
      tag: docker/tag

- name: build-helm
  plan:
  - aggregate:
    - get: ci
    - get: src
    - get: 12h
      trigger: true
  - task: build
    tags: [containerization]
    file: ci/pipelines/cf-operator/tasks/build-helm.yml
