resources:
- name: src
  type: git
  tags: [containerization]
  source:
    uri: ((src-repo))
    branch: master
- name: ci
  type: git
  tags: [containerization]
  source:
    uri: ((ci-repo))
    branch: ((ci-branch))
- name: 12h
  type: time
  source:
    interval: 12h

jobs:
- name: test
  serial: true
  serial_groups: [go-cache]
  plan:
  - aggregate:
    - get: ci
    - get: src
    - get: 12h
      trigger: true
  - task: vet
    tags: [containerization]
    configuration: (( load "../../common/tasks/vet.yml" ))
  - task: lint
    tags: [containerization]
    configuration: (( load "../../common/tasks/lint.yml" ))
  - task: test-unit
    tags: [containerization]
    configuration: (( load "../../common/tasks/test.yml" ))
  - task: test-integration
    tags: [containerization]
    params:
      ibmcloud_apikey: ((ibmcloud.key-value))
      ibmcloud_server: ((ibmcloud.server))
      ibmcloud_region: ((ibmcloud.region))
      ibmcloud_cluster: ((ibmcloud.cluster))
    configuration: (( load "../../common/tasks/test-integration.yml" ))

- name: build
  serial: true
  serial_groups: [go-cache]
  plan:
  - aggregate:
    - get: ci
    - get: src
    - get: 12h
      trigger: true
  - task: build
    tags: [containerization]
    configuration: (( load "../../common/tasks/build.yml" ))

- name: build-helm
  plan:
  - aggregate:
    - get: ci
    - get: src
    - get: 12h
      trigger: true
  - task: build
    tags: [containerization]
    configuration: (( load "../../common/tasks/build-helm.yml" ))
