---
resources:
- name: scf-pub-github-repo
  tags: [containerization]
  type: git
  check_every: 60m
  source:
    uri: https://github.com/SUSE/scf.git
    branch: 2.14.3
    git_config:
    - name: submodule.fetchJobs
      value: 128

- name: scf-helm-charts
  tags: [containerization]
  type: s3
  check_every: 5m
  source:
    disable_ssl: true
    bucket: unique-bbuccket
    endpoint: ((cos-endpoint))
    regexp: scf-(.*)-helm.tar.gz
    access_key_id: ((cos-access-key-id))
    secret_access_key: ((cos-secret-access-key))

jobs:
- name: scf-build
  plan:
  - get: scf-pub-github-repo
    tags: [containerization]
    trigger: true
    params: { submodules: all }
  - task: scf-build
    tags: [containerization]
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: havener/build-environment
          tag: latest
      inputs:
      - name: scf-pub-github-repo
      outputs:
      - name: helm-chart-store
      #
      # WIP: need to define where exactly to push the images, our current IBM container registry will not have enough quota for amount of images.
      # params:
      #   REGISTRY_ENDPOINT: ((private-registry-hostname))
      #   REGISTRY_USERNAME: ((private-registry-docker-username))
      #   REGISTRY_PASSWORD_RW: ((private-registry-docker-password-read-write))
      #   REGISTRY_PASSWORD_RO: ((private-registry-docker-password-read-only))
      #   REGISTRY_NAMESPACE: ((private-registry-namespace))
      run:
        path: /bin/bash
        args:
        - -c
        - (( file "scripts/build.sh" ))
  - put: scf-helm-charts
    tags: [cfee]
    attempts: 5
    params:
      file: helm-chart-store/scf-*-helm.tar.gz
