resources:
- name: src
  type: git
  source:
    uri: "https://github.com/cloudfoundry-incubator/cf-operator.git"
    branch: "master"
- name: ci
  type: git
  source:
    uri: ((ci-repo))
    branch: "rohit/kind"


jobs:
- name: test
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: src
      trigger: true
  - do:
    - task: test-integration
      privileged: true
      params:
        ssh_server_ip: ((ssh-server.ip))
        ssh_server_user: ((ssh-server.user))
        ssh_server_key: ((ssh-server.key))
        OPERATOR_TEST_STORAGE_CLASS: ((storageclass))
        DOCKER_IMAGE_REPOSITORY: ((docker-repo))
        DOCKER_IMAGE_TAG: "v0.0.0-0.gcd0b725b"
        GOPROXY: ((goproxy))
        NODES: 6
      file: ci/pipelines/tasks-kind/test-integration.yml
