---
platform: linux
image_resource:
 type: docker-image
 source:
   repository: cfcontainerization/go-tools
   tag: latest
inputs:
- name: src
  path: src/code.cloudfoundry.org/cf-operator
- name: ci
outputs:
- name: helm-chart
caches:
- path: pkg/mod # Persist go modules cache
run:
  path: ci/pipelines/cf-operator/tasks/build-helm.sh
